const ActionsConstant = {
  SET_AUTH_TOKEN: "SET_AUTH_TOKEN",
  SET_USER_LOGIN: "SET_USER_INFOR",
  SET_PLATFORM_SELECTED: "SET_PLATFORM_SELECTED",
  SET_DETAIL_PLATFORM: "SET_DETAIL_PLATFORM",
};

export default ActionsConstant;
